name: Guardami
favicon: null
layout_spectrum: 0.50167
typography_spectrum: 0.15109
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#876a48'
    - '#130a03'
    - '#4a3b29'
    - '#f5f5f5'
    - '#d49d62'
  brandStrength: 0.1875
  lightness: 0.19050744036212564
  saturation: 0.17274142755195498
  rhythmicContrast: 0.33912749495357275
purpose: []
